spring:
  application:
    name: battle-debrief
  profiles:
    default: dev
  jpa:
    open-in-view: false
  data:
    web:
      pageable:
        max-page-size: 100

server:
  port: ${SERVER_PORT:8080}

integration:
  barmory:
    base-url: ${BARMORY_BASE_URL:https://barmory.net}
    version: ${BARMORY_VERSION:8.4}
  battlegroup:
    base-url: ${BATTLEGROUP_BASE_URL:https://battlegroup.website/cgi-bin/api.py}
    match-base-url: ${BATTLEGROUP_MATCH_BASE_URL:https://s3.brokenarrowgame.tech/fights}

security:
  jwt:
    issuer: battle-debrief
    expiration: ${JWT_EXPIRATION:PT1H}
    secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
