spring:
  application:
    name: battle-debrief
  profiles:
    default: dev
  jpa:
    open-in-view: false
  data:
    web:
      pageable:
        max-page-size: 100

server:
  port: ${SERVER_PORT:8080}

security:
  jwt:
    issuer: battle-debrief
    expiration: ${JWT_EXPIRATION:PT1H}
    secret: ${JWT_SECRET}
